In [4]:
# Lists cannot be multiplied together.
list_a = [1, 2, 3]
list_b = [2, 4, 6]
#list_a * list_b (Error)

#Should be
list_c = []
for i in range(len(list_a)):
    list_c.append(list_a[i] * list_b[i])

list_c

[2, 8, 18]

In [5]:
#More easy, clean and speed way

import numpy as np

# Convert lists to arrays.
array_a = np.array(list_a)
array_b = np.array(list_b)

# Perform element-wise multiplication between the arrays.
array_a * array_b

array([ 2,  8, 18])

In [6]:
#Creating a 1D array
import numpy as np

array_1d = np.array([1, 2, 3])
array_1d

array([1, 2, 3])

In [7]:
#Creating a 2D array
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [10]:
np.full((5, 3), 8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [11]:
#Multidimentional to one dimentional

array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()
array_2d.flatten()

[[1 2 3]
 [4 5 6]]



array([1, 2, 3, 4, 5, 6])

In [12]:
#Reshape
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()
array_2d.reshape(3, 2)

[[1 2 3]
 [4 5 6]]



array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
#Calculate miss dimension automatically
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()
array_2d.reshape(3, -1)

[[1 2 3]
 [4 5 6]]



array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
#Convert to list
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()
new_arr = array_2d.tolist()

type(new_arr)

[[1 2 3]
 [4 5 6]]



list

In [17]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print()

print(a.max()) #maximum value
print(a.mean()) #mean value
print(a.min()) #minimum value
print(a.std()) #standard deviation

[[1 2 3]
 [4 5 6]]

6
3.5
1
1.707825127659933


In [18]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()

print(array_2d.shape) #Shape of the array
print(array_2d.dtype) #Type in numpy
print(array_2d.size) #Number of elements
print(array_2d.T) #Transpose

[[1 2 3]
 [4 5 6]]

(2, 3)
int64
6
[[1 4]
 [2 5]
 [3 6]]


In [19]:
#accessing items
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print()

print(a[1])
print(a[0, 1])
print(a[1, 2])

[[1 2 3]
 [4 5 6]]

[4 5 6]
2
6


In [20]:
#Accessing subarrays
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print()

a[:, 1:]

[[1 2 3]
 [4 5 6]]



array([[2, 3],
       [5, 6]])

In [27]:
#Math
a = np.array([(1, 2, 3), (4, 5, 6)])
b = np.array([[1, 2, 3], [1, 2, 3]])

print(f'a) \n {a}', end='\n\n')
print(f'b) \n {b}', end='\n\n')
print(f'a + b) \n {a + b}', end='\n\n')
print(f'a - b:) \n {a - b}')

a) 
 [[1 2 3]
 [4 5 6]]

b) 
 [[1 2 3]
 [1 2 3]]

a + b) 
 [[2 4 6]
 [5 7 9]]

a - b:) 
 [[0 0 0]
 [3 3 3]]


In [28]:
#Arrays are changable
a = np.array([(1, 2), (3, 4)])
print(a)
print()

a[1][1] = 100
a

[[1 2]
 [3 4]]



array([[  1,   2],
       [  3, 100]])

In [29]:
#Not length just content or shape
a = np.array([1, 2, 3])
print(a)
print()

a[3] = 100
a

[1 2 3]



IndexError: index 3 is out of bounds for axis 0 with size 3